---
output:
  html_document:
    df_print: paged
  pdf_document: default
urlcolor: blue
header-includes:
- \usepackage{lastpage}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[CO, CE]{Yian Wang}
- \fancyfoot[CO, CE]{\thepage \ of \pageref{LastPage}}
---

```{r setup, message = FALSE, echo=FALSE}

packages_needed <- c("tidyverse", "googledrive", "readxl", "janitor", 
                     "lubridate", "opendatatoronto", "ggthemes")

package.check <- lapply(
  packages_needed,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
    }
  }
)

# Credit: package.check based on a helpful post from Vikram Baliga https://vbaliga.github.io/verify-that-r-packages-are-installed-and-loaded/

# Load tidyverse
library(tidyverse)
library(readxl)
library(janitor)
library(opendatatoronto)
library(ggthemes)

knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), echo = TRUE)
```


```{r getdata, eval = FALSE, echo=FALSE}

# Get the data neighbourhood data from Open Data Toronto.

nbhoods_shape_raw <- list_package_resources("neighbourhoods") %>% 
  get_resource()

saveRDS(nbhoods_shape_raw, "data/neighbourhood_shapefile.Rds")

nbhood_profile <- search_packages("Neighbourhood Profile") %>%
  list_package_resources() %>% 
  filter(name == "neighbourhood-profiles-2016-csv") %>% 
  get_resource()

saveRDS(nbhood_profile, "data/neighbourhood_profile.Rds")
```


```{r load_data, echo = FALSE}

# Load the COVID data downloaded from Toronto City

daily_data <- "CityofToronto_COVID-19_Daily_Public_Reporting.xlsx"

# Cases reported by date
reported_raw <- read_excel(daily_data, sheet = 5) %>% 
  clean_names()

# Cases by outbreak type
outbreak_raw <- read_excel(daily_data, sheet = 3) %>% 
  clean_names()

# Data last updated date
date_daily <- read_excel(daily_data, sheet = 1) %>% 
  clean_names()

# By neighbourhood
neighbourood_data <- "CityofToronto_COVID-19_NeighbourhoodData.xlsx"

# Cases reported by date
nbhood_raw <- read_excel(neighbourood_data, sheet = 2) %>% 
  clean_names()

# Date the neighbourhood data was last updated
date_nbhood <- read_excel(neighbourood_data, sheet = 1) %>% 
  clean_names()

rm(daily_data, neighbourood_data)

# Load the neighbourhood data from Toronto City.

# Get neighbourhood profile data
nbhood_profile <- readRDS("data/neighbourhood_profile.Rds")

# Get shape data for mapping 
nbhoods_shape_raw <- readRDS("data/neighbourhood_shapefile.Rds") %>% 
  sf::st_as_sf() ## Make sure shape info is in the most up to date format

```

Code last run `r Sys.Date()`.  
Daily: `r date_daily[1,1]`.   
Neighbourhood: `r date_nbhood[1,1]`. 

# Daily cases
## Data wrangling

```{r cases_dw}
library(lubridate)
library(stringr)
library(forcats)

#create new dataset
reported_int <- reported_raw %>%
  mutate_if(is.numeric, replace_na, replace = 0) %>% #resolve NAs
  mutate(reported_date = date(reported_date)) # make sure reported_date in date format

#tidy data
reported <- reported_int %>% 
  pivot_longer(-(reported_date), names_to = "case_type", values_to = "quantity") %>% 
  mutate(case_type = str_to_title(case_type)) %>% 
  select(reported_date,case_type, quantity) %>% 
  mutate(case_type = fct_relevel(case_type, "Deceased", after = 2)) #reorder case_type
```

\newpage
## Data visualization

```{r cases_vis}
#plot the data as stacked histogram
reported %>% 
  ggplot(aes(x=reported_date, y=quantity, fill = case_type)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Cases reported by day in Toronto, Canada", 
       subtitle = "Confirmed and probable cases",
       scale_x_continuous(limits =c(date("2020-01-01"), Sys.Date())),
       x = "Date", 
       y = "Case count",
       caption = str_c("Created by: Yian Wang \n Source: Ontario Ministry of Health, ",
                       "Integrated Public Health Information System and CORES\n", 
                       date_daily[1,1])) +
  theme(legend.title = element_blank(), legend.position =c(0.15, 0.8)) +
  scale_y_continuous(limits =c(0, 2000), breaks = seq(0, 2000, by = 500)) +
  scale_x_date(labels = scales::date_format("%d %b %y"), limits = 
                 c(date("2020-01-01"), Sys.Date())) +
  scale_fill_manual(values = c("#FF89C6", "#B0DCB1", "#686FFF")) # set bar colours
```

\newpage
# Outbreak Type
## Data wrangling

```{r outbreak_dw, echo = TRUE}
# create new dataset 
outbreak <- outbreak_raw %>% 
  mutate(episode_week = date(episode_week)) %>% # make sure episode_week in correct date format
  mutate(outbreak_or_sporadic = str_replace(outbreak_or_sporadic, "OB A", "Outbreak a")) # specify OB = outbreak

outbreak <- outbreak %>%  
  group_by(episode_week) %>% 
  mutate(outbreak_or_sporadic = fct_rev(outbreak_or_sporadic)) %>% #change order of variables better for visualization
  mutate(total_cases = sum(cases)) #new variable to indicate total number of cases in episode week
```

\newpage
## Data visualization

```{r outbreak_vis}
# plot data as stacked bar chart
outbreak %>% 
  ggplot(aes(x=episode_week, y=cases, fill = outbreak_or_sporadic)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Cases by outbreak type and week in Toronto, Canada", 
       subtitle = "Confirmed and probable cases",
       scale_x_date(labels = scales::date_format("%d %b %y"), limits = 
                      c(date("2020-01-01"), Sys.Date() + 7)),
       scale_x_continuous(limits = c(date("2020-01-01"), Sys.Date() + 7)),
       x = "Date", 
       y = "Case count",
       caption = str_c("Created by: Yian Wang \n Source: Ontario Ministry of Health, ",
                       "Integrated Public Health Information System and CORES\n",
                       date_daily[1,1])) +
  theme(legend.title = element_blank(), legend.position =c(0.15, 0.8)) +
  scale_y_continuous(limits =c(0, max(outbreak$total_cases)), 
                     breaks = seq(0, max(outbreak$total_cases), by = 2000)) +
  scale_x_date(labels = scales::date_format("%d %b %y"), 
               limits = c(date("2020-01-01"), Sys.Date())) +
  scale_fill_manual(values = c("#8BDDD9", "#C59BFE"))
```

\newpage
# Task 3: Neighbourhoods
## Data wrangling: part 1

```{r nbhood_dw_1}
income <- nbhood_profile %>% 
  filter(str_detect(Topic, "Low income")) %>% # isolate rows only by low income 
  filter(str_detect(Characteristic, "18 to 64")) %>% # isolate rows by ages 18-64
  filter(str_detect(Characteristic, "%")) %>% # isolate by percentages only
  filter(`_id`==1143) %>% # we want to use id 1143 as its surrounding rows in the dataset make more intuitive sense
  select(-c(`Category`,`Topic`,`Data Source`,`Characteristic`,`City of Toronto`)) %>% 
  pivot_longer(-`_id`, names_to = "neighbourhood", values_to="percentage_low_income")%>% #tidying data
  mutate(percentage_low_income = as.double(percentage_low_income))
```

## Data wrangling: part 2

```{r nbhood_dw_2}
nbhoods_int <- nbhoods_shape_raw %>% 
  mutate(neighbourhood_name = str_remove(AREA_NAME, "\\s\\([^()]*\\)$")) #tidying 

# fix discrepancies between datasets
nbhoods_int <- nbhoods_int %>% 
  mutate(neighbourhood_name=str_replace(neighbourhood_name,"Pellam", "Pelham")) %>% 
  mutate(neighbourhood_name=str_replace(neighbourhood_name,"St.James", "St. James"))
  
#remove NA row (does not fall in 140 neighbourhoods in TO)
nbhood_raw <- nbhood_raw %>% 
  na.omit()

# merge so we have 100,000 people by nbhd
nbhd_merge <- nbhoods_int %>% 
  left_join(nbhood_raw, by = "neighbourhood_name")
   
# merge so we have the low income variables
nbhoods_all <- nbhd_merge %>% 
  right_join(income, by = c("neighbourhood_name"="neighbourhood")) %>% 
  select("neighbourhood_name", "rate_per_100_000_people", "percentage_low_income") %>% 
  rename(`rate_per_100000`=`rate_per_100_000_people`) #rename rate variable - simplify
```

## Data wrangling: part 3

```{r nbhood_dw_3}

nbhoods_final <- nbhoods_all %>% 
  mutate(med_inc = median(percentage_low_income)) %>% # create new variable of median percentage low income
  mutate(med_rate = median(rate_per_100000)) %>% # create new variable of median rate per 100,000
  mutate(nbhood_type = case_when( #create new variable with 4 cases
    percentage_low_income >= med_inc & rate_per_100000 >= med_rate ~ "Higher low income rate, higher case rate",
    percentage_low_income >= med_inc & rate_per_100000 < med_rate  ~ "Higher low income rate, lower case rate",
    percentage_low_income < med_inc & rate_per_100000 >= med_rate  ~ "Lower low income rate, higher case rate",   
    percentage_low_income < med_inc & rate_per_100000 < med_rate  ~ "Lower low income rate, lower case rate"
  ))
```

\newpage
## Data visualization

```{r neighbourhood_graphs_1, fig.height=4}
# map percentage of 18 to 64 year olds living in a low income family in TO
ggplot(data = nbhoods_final) +
  geom_sf(aes(fill = percentage_low_income)) +
  theme_map() +
  labs(title = "Percentage of 18 to 64 year olds living in a low income family (2015)", 
       subtitle = "Neighbourhoods of Toronto, Canada",
       caption = str_c("Created by: Yian Wang, \n Source: ",
                       "Ontario Ministry of Health, Integrated Public Health ",
                       "Information System and CORES\n", date_daily[1,1])) +
  theme(legend.position = "right") +
  scale_fill_gradient(name="% low income", low = "blue", high = "lightgrey")
```

\newpage

```{r neighbourhood_graphs_2, fig.height=4}
# map COVID-19 cases per 100,000, by neighbourhood in TO
ggplot(data = nbhoods_final) +
  geom_sf(aes(fill = rate_per_100000)) +
  theme_map() +
  labs(title = "COVID-19 cases per 100,000, by neighbourhood in Toronto, Canada", 
       caption = str_c("Created by: Yian Wang for STA303/1002, U of T \n Source: ",
                       "Ontario Ministry of Health, Integrated Public Health ",
                       "Information System and CORES\n", date_daily[1,1])) +
  theme(legend.position = "right") +
  scale_fill_gradient(name="Cases per 100,000 people", low = "#FBE5FC", high = "#F300FF")
```

\newpage

```{r neighbourhood_graphs_3, fig.height=5, fig.width=9}
# map COVID-19 cases per 100,000, by TO neighbourhood
ggplot(data = nbhoods_final) +
  geom_sf(aes(fill = nbhood_type)) +
  theme_map() +
  labs(title = "COVID-19 cases per 100,000, by neighbourhood in Toronto, Canada", 
       caption = str_c("Created by: Yian Wang \n Source: ",
                       "Ontario Ministry of Health, Integrated Public Health ",
                       "Information System and CORES\n", date_daily[1,1])) +
  theme(legend.position = "right") +
  scale_fill_brewer(name="% of 18 to 64 year-olds in low income families and COVID-19 case rates", palette = "Pastel1")
```